# render.yaml
services:
  - type: web
    name: Finn
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.10.15
      - key: ANTHROPIC_API_KEY
        sync: false 
      - key: GEMINI_API_KEY
        sync: false
      - key: NEWS_API_KEY
        sync: false
      - key: GEMINI_NEWS_KEYS
        sync: false